version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: ride-request-service
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/ride-request-db
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_RABBITMQ_VIRTUAL_HOST: /
      SPRING_RABBITMQ_CONNECTION_TIMEOUT: 30000
      SPRING_DATA_MONGODB_AUTO_INDEX_CREATION: 'true'
      MAX_DISTANCE: 1000
      SPRINGDOC_API_DOCS_ENABLED: 'true'
      SPRINGDOC_SWAGGER_UI_ENABLED: 'true'
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html

volumes:
  mongo-data:
